name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: npm install
        run: |
          cd bloglist-frontend
          npm install
          cd ..
          cd bloglist-backend
          npm install
          cd ..
