name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
  SECRET: ${{ secrets.SECRET }}
jobs:
  deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: npm install
        run: |
          cd bloglist-frontend
          npm install
          cd ../bloglist-backend
          npm install
      # - name: lint
      #   run: |
      #     cd bloglist-frontend
      #     npm run lint
      #     cd ../bloglist-backend
      #     npm run lint
      - name: build
        run: npm run build:ui
        working-directory: ./bloglist-backend
      # - name: test
      #   run: |
      #     cd bloglist-frontend
      #     npm run test:once
      #     cd ../bloglist-backend
      #     npm run test
      # - name: start backend in the background
      #   run: cd bloglist-backend && npm run start:test &
      # - name: e2e tests
      #   uses: cypress-io/github-action@v5
      #   with:
      #     working-directory: bloglist-frontend
      #     start: npm start
      #     command: npm run test:e2e
      #     wait-on: http://localhost:3000, http://localhost:3003/api/blogs
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        working-directory: ./bloglist-backend
